# Generated by Django 3.0.6 on 2020-06-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('members', '0003_auto_20200609_1604'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='activate_index',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['id', 'is_active'], name='activate_index'),
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
