# Generated by Django 3.0.6 on 2020-06-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20200611_1608'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='activate_index',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'id'], name='activate_index'),
        ),
    ]
