# Generated by Django 3.0.6 on 2020-06-11 08:01

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('members', '0006_auto_20200611_1639'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='keyword',
            table='keyword',
        ),
    ]
